USE [master]
GO
/****** Object:  Database [biometrics]    Script Date: 3/2/2017 2:05:03 AM ******/
CREATE DATABASE [biometrics]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'biometrics', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER12\MSSQL\DATA\biometrics.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'biometrics_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER12\MSSQL\DATA\biometrics_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [biometrics] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [biometrics].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [biometrics] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [biometrics] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [biometrics] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [biometrics] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [biometrics] SET ARITHABORT OFF 
GO
ALTER DATABASE [biometrics] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [biometrics] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [biometrics] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [biometrics] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [biometrics] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [biometrics] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [biometrics] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [biometrics] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [biometrics] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [biometrics] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [biometrics] SET  DISABLE_BROKER 
GO
ALTER DATABASE [biometrics] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [biometrics] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [biometrics] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [biometrics] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [biometrics] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [biometrics] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [biometrics] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [biometrics] SET RECOVERY FULL 
GO
ALTER DATABASE [biometrics] SET  MULTI_USER 
GO
ALTER DATABASE [biometrics] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [biometrics] SET DB_CHAINING OFF 
GO
ALTER DATABASE [biometrics] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [biometrics] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [biometrics]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 3/2/2017 2:05:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](20) NULL,
	[LastName] [varchar](20) NULL,
	[Thumb] [image] NULL,
	[DateAdded] [datetime] NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
USE [master]
GO
ALTER DATABASE [biometrics] SET  READ_WRITE 
GO
